### ISSUE TITLE
jszip module not found

### ISSUE THREAD

**Issue by vfulco** [monteno-m/job-scraper#1]
Fairly new in serverless world and most of my early lessons have come from node.js side.

Git cloned repo, installed serverless-python-requirements (the latest) and when I try to deploy, get the error:
  
Serverless plugin "serverless-python-requirements" initialization errored: Cannot find module 'jszip'

Tried omitting the module in serverless.yml to see if I could get further along but stops in same place. Also when I do a npm list, jszip is version 3.1.5.  Googling around doesn't surface other cases.

Thanks for any trailheads!

Environment Information -----------------------------
OS:                     linux / Ubuntu 18.04
Node Version:           8.10.0
Serverless Version:     1.37.1

**Comment by monteno-m** [comment]
Hey, haven't been able to look at this since I've been busy but this was done as a student project, when I get some free time I'll get around to checking it out thanks.

**Comment by weisisheng** [comment]
No worries. It makes a great lesson for serverless noobs.  I will be free end of week and returning to testing it some more. Thanks for your valuable time.

**Comment by weisisheng** [comment]
I updated all python requirements and can deploy now.

Using beautifulsoup4==4.7.1 and requests==2.21.0

**Comment by vfulco** [comment]
Apologies, swapping between personal and biz accounts.

**Comment by monteno-m** [comment]
Thats good that you figured out it was versioning - I thought it might be that but wasn't able to test. Regardless hopefully this repo can help you somehow, helped me a lot when writing it to understand serverless and AWS Lambda
